### PR TITLE
Add support for multiple docker credentials

### PR DESCRIPTION
**Pull request by Eryalito**

### CODE REVIEW

**Comment by Eryalito** [comment]
I have come across several scenarios where I needed to authenticate against multiple registries, which can not be done with the current user/pass/registry configuration. I thought it could be nice to add this feature upstream for people working with private registries or in air gaped environments. 

I'll share three of the scenarios I've faced.

- Source image is from a different one than push registry.
- Multiple sources images from distinct registries.
- Same source and destination registry but multiple credentials (one for pull and another for push)

**Comment by Eryalito** [comment]
> Hey @Eryalito
> 
> how is the syntax in the `.drone.yml`. I think it should be:
> 
> ```
> - name: build-docker-dev
>   image: image.**.dev/plugins/kaniko-multi-cred
>   depends_on: [ clone ]
>   environment:
>     JKLY_URL: https://**.dev
>   settings:
>     credentials:
>       - <user>:<pass>@image.**.dev
>       - <user>:<pass>@docker-push-test.**.dev
>       - <user>:<pass>@docker-push-prod.**.dev
>     username:
>       from_secret: image-dev-user
>     password:
>       from_secret: image-dev-pw
>     repo: docker-push-test.**.dev/lp
>     tags:
>     - dev
>     registry: docker-push-test.**.dev
>     dockerfile: Dockerfile
> ```
> 
> Can we retrieve the list of credentials from drone secrets?

Yes, you can retrieve it from a drone secret, but it's a bit tricky.

I have not found docs about settings/environment arrays, and as far a I know drone does not support secrets on those so you have to define a single gigantic secret concatenating all of the elements separated by comma. I think it would be something like this:

Create the Drone secret `my-creds`:
`<user>:<pass>@image.**.dev,<user>:<pass>@docker-push-test.**.dev,<user>:<pass>@docker-push-prod.**.dev`

And the step:

```yaml
- name: build-docker-dev
  image: image.**.dev/plugins/kaniko-multi-cred
  depends_on: [ clone ]
  environment:
    JKLY_URL: https://**.dev
  settings:
    credentials:
      from_secret: my-creds
    username:
      from_secret: image-dev-user
    password:
      from_secret: image-dev-pw
    repo: docker-push-test.**.dev/lp
    tags:
    - dev
    registry: docker-push-test.**.dev
    dockerfile: Dockerfile
```

**Comment by ykorzikowski** [comment]
I found a better solution (even working without your PR): 

On your local machine, do all the docker login commands that are needed. 

Then create a drone secret with your `~/.docker/config.json` and add it like this to theenvironment. 

```
environment:
  PLUGIN_CONFIG:
    from_secret: image-swokiz-dev-json
```

**Comment by Eryalito** [comment]
Yeah, I've seen that they added the feature after this change, on PR #67
 
As this is already solved upstream I'm closing this PR.

**Pull request closed without merging**
